//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class openspace:public drogon::DrTemplate<openspace>
{
public:
	openspace(){};
	virtual ~openspace(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
